
export {default as PreLogin} from './PreLogin/PreLogin'
export {default as LoginWithPhone} from './LoginWithPhone/LoginWithPhone'
export {default as LoginWithEmail} from './LoginWithEmail/LoginWithEmail'
export {default as ForgetPassword} from './ForgetPassword/ForgetPassword'
export {default as NewPassword} from './NewPassword/NewPassword'
export {default as Signup} from './SignUp/SignUp'
export {default as CompleteProfile} from './CompleteProfile/CompleteProfile'
export {default as ChangePassword} from './ChangePassword/ChangePassword'
export {default as Home} from './Home/Home'
export {default as Coupons} from './Coupons/Coupons'
export {default as OfferDetails} from './OfferDetails/OfferDetails'
export {default as Profile} from './Profile/Profile'
export {default as Notifications} from './Notifications/Notifications'
export {default as TermsAndConditions} from './TermsAndConditions/TermsAndConditions'
export {default as PrivacyPolicy} from './PrivacyPolicy/PrivacyPolicy'
export {default as EditProfile} from './EditProfile/EditProfile'
export {default as CouponDetails} from './EditProfile/EditProfile'
