export default {
    // showeye: require('../assets/images/show.png'),
    // hideEye: require('../assets/images/hide.png'),
    icBack: require('../assets/Icons/back.png'),
    // icForward: require('../assets/images/forward.png'),
    // activeCheck: require('../assets/images/check.png'),
    // inActiveCheck: require('../assets/images/unchecked.png'),
    // lock: require('../assets/images/lock.png'),
    // home: require('../assets/images/home.png'),
    // profile: require('../assets/images/profile.png'),
    // booking: require('../assets/images/booking.png'),
    // location: require('../assets/images/location.png'),
    // notification: require('../assets/images/notification.png'),
    menu: require('../assets/Icons/menu.png'),
    email: require('../assets/Icons/email.png'),
    phone: require('../assets/Icons/phone.png'),
    apple: require('../assets/Icons/apple.png'),
    facebook: require('../assets/Icons/facebook.png'),
    google: require('../assets/Icons/google.png'),

}