export default {
    CHANGE_PASSWORD: "ChangePassword",
    COMPLETE_PROFILE: "CompleteProfile",
    COUPON_DETAILS: "Coupon_Details",
    EDIT_PROFILE: "EditProfile",
    FORGET_PASSWORD: "ForgetPassword",
    LOGIN_WITH_EMAIL: "LoginWithEmail",
    LOGIN_WITH_PHONE: "LoginWithPhone",
    NEW_PASSWORD: "NewPassword",
    OFFER_DETAILS: "OfferDetails",
    PRE_LOGIN: "PreLogin",
    TERMS_AND_CONDITIONS: "TermsAndConditions",
    PRIVACY_POLICY: "PrivacyPolicy",
    SIGN_UP: "SignUp",
    HOME: "Home",
    COUPONS: "Coupons",
    NOTIFICATIONS: "Notifications",
    PROFILE: "Profile",
    VERIFICATION: "Verification"
}